### ISSUE TITLE
怎么处理除了scienceqa之外的数据集？

### ISSUE THREAD

**Issue by 2018211801** [GCYZSL/MoLA#1]
你好，我对您的项目非常感兴趣，我在复现的过程中发现preparation_scienceqa_data.py不能处理其他数据集文件。请问可以提供一下吗？谢谢

**Comment by GCYZSL** [comment]
谢谢您对项目感兴趣，我们在data preparation 中对训练需要的格式做了说明。只需要把其他数据集处理成相应格式就好了。可以参考我们对[ScienceQA](https://github.com/GCYZSL/MoLA/blob/main/preparation_scienceqa_data.py)的数据处理。

**Comment by 2018211801** [comment]
> 谢谢您对项目感兴趣，我们在data preparation 中对训练需要的格式做了说明。只需要把其他数据集处理成相应格式就好了。可以参考我们对[ScienceQA](https://github.com/GCYZSL/MoLA/blob/main/preparation_scienceqa_data.py)的数据处理。
浅浅处理了一下发现有很多格式错误。或者可不可以把处理好的数据发到我的邮箱 2201210409@stu.pku.edu.cn 呀？感谢作者！

**Comment by GCYZSL** [comment]
已发送！下载连接是：https://drive.google.com/file/d/1-AHDmTKnds9JTJPFr1CFCqneGjj1HB0M/view?usp=sharing
