### ISSUE TITLE
您好请问训练需要几张卡多大的显存啊

### ISSUE THREAD

**Issue by sunrise224** [GCYZSL/MoLA#14]
scienceqa训练我用一张80g的（还剩50g）试了试不够

**Comment by GCYZSL** [comment]
应该是48G 左右， 就够了。 您可以试试 minibatch_size 减少一个么？谢谢

**Comment by sunrise224** [comment]
作者您好，我通过图上的设置想在两张还剩接近40g的卡上并行，但是会出现如图的错误，请问有什么可能的解决办法吗。
![WechatIMG817](https://github.com/GCYZSL/MoLA/assets/145143067/270ee982-4169-453b-b4d4-3920e2432328)
![WechatIMG816](https://github.com/GCYZSL/MoLA/assets/145143067/6a7db8c5-5641-4277-9977-9f4daacdace7)

**Comment by GCYZSL** [comment]
我看报错也是显存装不下，您可以试试再把minibatchsize减少一些，谢谢！

**Comment by suchenyang2023** [comment]
谢谢，我刚才单卡空出来70g了都装不下sample mola_training.py，和您说的48g差距有点大。 bs和microbs也调小到了96，6，看来需要进一步调小？ 
<img width="1133" alt="image" src="https://github.com/GCYZSL/MoLA/assets/145143067/e73a96fc-1487-4bb2-83b2-11b44e01efc6">

**Comment by GCYZSL** [comment]
我感觉可能是设置的问题，您可以确定下是否卡里放的是6个samples。
