### ISSUE TITLE
作者您好，想问一下在推理时，是把每一个LoRA的权重都融入进pretrained weights中吗

### ISSUE THREAD

**Issue by suntea233** [GCYZSL/MoLA#19]
但是训练时却又是按照router分配权重，这种推理时与训练时不一致会导致模型性能变差吗？

**Comment by GCYZSL** [comment]
您好，谢谢您的提问！您的理解是对的，在推理是不是把LoRA的权重融入进pretrained model，因为存在router，所以需要计算每个experts的权重。因此，模型的性能保持。谢谢！

**Comment by suntea233** [comment]
哦哦哦，那就是推理时与训练时保持一致是吗，没有执行merge的操作？

**Comment by GCYZSL** [comment]
是的！

**Comment by suntea233** [comment]
好的好的，谢谢！
