### ISSUE TITLE
工作是好工作，就是代码太屎山了

### ISSUE THREAD

**Issue by whwangovo** [GCYZSL/MoLA#4]
花了一天整理了一下你们的代码，确实太难读了，很多地方 copy transformers 库直接进行修改（好在有##modify）。好像里面还有你们其他工作相关的代码（
如果可以把代码稍微整理一下的话就很好了～非常有意义的工作，感谢！

**Comment by GCYZSL** [comment]
谢谢您的建议和支持！我们有时间会整理代码，确保更加的清晰和易于修改。再次感谢您的支持！

**Comment by small-noob** [comment]
> 花了一天整理了一下你们的代码，确实太难读了，很多地方 copy transformers 库直接进行修改（好在有##modify）。好像里面还有你们其他工作相关的代码（ 如果可以把代码稍微整理一下的话就很好了～非常有意义的工作，感谢！

请问是否可以公开您整理好的代码以促进开源社区的良性发展~感谢！
